name: Build

on:
  push:
    branches: [master]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    strategy:
      fail-fast: false

      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [windows-latest]
        target: [hkxcmpr, ProjectNewReignQtGUI]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Build and Upload Artifact
        uses: ./.github/actions/build-common
        with:
          target: ${{ matrix.target }}
          mode: release
          artifact_name: ${{ matrix.target }}-${{ matrix.os }}
